name: karsapapp.com
favicon: null
layout_spectrum: 0.4477454521693289
typography_spectrum: 0.59368
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: 'http://karsapapp.com/'
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1787552325986326
  lightness: 0.3102648705244064
  saturation: 0.3752434933558106
  rhythmicContrast: 0.6438612132333219
purpose: []
