name: karsapapp.com
favicon: null
layout_spectrum: 0.24106
typography_spectrum: 0.73957
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Me sharing some photos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: 'http://karsapapp.com/'
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6a6a6a'
    - '#313131'
    - '#9a9a9a'
    - '#0f0f0f'
    - '#c8c8c8'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
