title: Me sharing some photos
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.4749104
  lightness: 0.4390681
  brandColors:
    - '#1C1A27'
    - '#E3E7EA'
    - '#C98C6F'
    - '#87755F'
    - '#ACB0B3'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: 'http://karsapapp.com/'
  facebook: null
name: karsapapp.com
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.734767
layout_spectrum: 0.7311828
